spring.application.name=japanese_learning
spring.datasource.url = jdbc:mysql://localhost:3306/japanese_learning
spring.datasource.username = root
spring.datasource.password = 123456

# JPA Configuration
#spring.jpa.hibernate.ddl-auto=none
 spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=create-drop

# Show log SQL
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Gan gia tri tham so vao cau SQl
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE