// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTf99-RyvSTzIsUqeY4FlvARzh498088k',
    appId: '1:427992174717:web:461318727669a25dbf6114',
    messagingSenderId: '427992174717',
    projectId: 'japaneseapp-76a7d',
    authDomain: 'japaneseapp-76a7d.firebaseapp.com',
    storageBucket: 'japaneseapp-76a7d.firebasestorage.app',
    measurementId: 'G-DMP1D2QCJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFYbkE7_L-fPv509CvJmPFO2xMBWvP5hQ',
    appId: '1:427992174717:android:8c7f81c8b51644cabf6114',
    messagingSenderId: '427992174717',
    projectId: 'japaneseapp-76a7d',
    storageBucket: 'japaneseapp-76a7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChkaecugvvf6w7vmZXIFZ3z0Sar24sNWE',
    appId: '1:427992174717:ios:cc3307141fec4bafbf6114',
    messagingSenderId: '427992174717',
    projectId: 'japaneseapp-76a7d',
    storageBucket: 'japaneseapp-76a7d.firebasestorage.app',
    iosClientId: '427992174717-770rvbl2i6bpok98midebu3hue0hcm7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPrm393',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChkaecugvvf6w7vmZXIFZ3z0Sar24sNWE',
    appId: '1:427992174717:ios:cc3307141fec4bafbf6114',
    messagingSenderId: '427992174717',
    projectId: 'japaneseapp-76a7d',
    storageBucket: 'japaneseapp-76a7d.firebasestorage.app',
    iosClientId: '427992174717-770rvbl2i6bpok98midebu3hue0hcm7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPrm393',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTf99-RyvSTzIsUqeY4FlvARzh498088k',
    appId: '1:427992174717:web:8ae7ea2d18411997bf6114',
    messagingSenderId: '427992174717',
    projectId: 'japaneseapp-76a7d',
    authDomain: 'japaneseapp-76a7d.firebaseapp.com',
    storageBucket: 'japaneseapp-76a7d.firebasestorage.app',
    measurementId: 'G-ZWNZGE4E5W',
  );

}