// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACXpnE7t3Xawb7oUejPrdmdww1-UM8YJM',
    appId: '1:638373625149:web:21eb8d0bfa90e3f3275954',
    messagingSenderId: '638373625149',
    projectId: 'japaneselearning-ac804',
    authDomain: 'japaneselearning-ac804.firebaseapp.com',
    storageBucket: 'japaneselearning-ac804.firebasestorage.app',
    measurementId: 'G-JHBEFHXF6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhCiI_jJzxzWL1FH9RtX496gJJbKqKVkk',
    appId: '1:638373625149:android:591348cdd501931b275954',
    messagingSenderId: '638373625149',
    projectId: 'japaneselearning-ac804',
    storageBucket: 'japaneselearning-ac804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD99KHyVA6-gIfYJ365uJU4qx5g3l-C_3c',
    appId: '1:638373625149:ios:8bd0d9aa15c4a756275954',
    messagingSenderId: '638373625149',
    projectId: 'japaneselearning-ac804',
    storageBucket: 'japaneselearning-ac804.firebasestorage.app',
    iosBundleId: 'com.example.japaneseLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD99KHyVA6-gIfYJ365uJU4qx5g3l-C_3c',
    appId: '1:638373625149:ios:8bd0d9aa15c4a756275954',
    messagingSenderId: '638373625149',
    projectId: 'japaneselearning-ac804',
    storageBucket: 'japaneselearning-ac804.firebasestorage.app',
    iosBundleId: 'com.example.japaneseLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACXpnE7t3Xawb7oUejPrdmdww1-UM8YJM',
    appId: '1:638373625149:web:0322d1c63a48102d275954',
    messagingSenderId: '638373625149',
    projectId: 'japaneselearning-ac804',
    authDomain: 'japaneselearning-ac804.firebaseapp.com',
    storageBucket: 'japaneselearning-ac804.firebasestorage.app',
    measurementId: 'G-C1VG3WCGRX',
  );
}
